### ISSUE TITLE
unknown sources

### ISSUE THREAD

**Issue by moczix** [jarekb123/inject_dart_example#1]
![image](https://user-images.githubusercontent.com/37540008/57795196-a703be80-7745-11e9-8f1e-6d48ba9f5573.png)

Hello, look at the attachment ;d i cloned your repo, and tried to run it and got these errors.

Before i tried to run inject.dart on my own project but got the same issue, maybe you know what is wrong?

**Comment by jarekb123** [comment]
I don't see any errors in your log.
